fixes to rofi-randr

diff --git a/bin/rofi-randr b/bin/rofi-randr
--- a/bin/rofi-randr
+++ b/bin/rofi-randr
@@ -2,8 +2,6 @@
 #
 # Setup outputs with xrandr as a backend and dmenu as a frontend
 #
-# external commands: cat, cut, dmenu, grep, sed, xrandr
-# Released under GPLv2
 
 typeset XRANDR_TXT # readonly; stdout of running xrandr without any options
 typeset -A OUTPUT_CONFIGURED # key=connected output name
@@ -40,8 +38,7 @@ function main() {
 }
 
 ################################################################################
-# Uses dmenu to select an output. Skips menu if only 1 option is available.
-# Prints the name of the selected output to stdout
+# Select Output With Dmenu
 # Global variables:
 #  OUTPUT_CONFIGURED
 # Arguments:
@@ -49,7 +46,7 @@ function main() {
 #  $2=group of outputs. valid options are configured, unconfigured, all
 # Returns:
 #  257=bad arguments
-#  258=bad selection (TODO)
+#  258=bad selection 
 #  259=no options available
 ################################################################################
 function select_output() {
@@ -82,17 +79,14 @@ function select_output() {
 }
 
 ################################################################################
-# Uses dmenu to select the position of a given output relative to an already
-# configured output. --same-as and --off are considered a position.
-# Prints in the form of xrandr option (eg, '--right-of DP1') to stdout
-# Global variables:
-#  OUTPUT_CONFIGURED
+# Relative Positioning As Compared to Already Configured Monitors 
 # Arguments:
 #  $1=name of output to configure
 # Returns:
-#  257=bad argument (TODO: check validity beyond existance)
+#  257=bad argument 
 #  258=bad selection
 #  259=no configured outputs to relate to (ie, no anchor)
+
 ################################################################################
 function select_position() {
   local anchor
@@ -125,17 +119,11 @@ off" | rofi -dmenu -l 10 -p "Select position of $1:" | read selection
 }
 
 ################################################################################
-# Uses dmenu to display the detected mode options for a given output and lets
-# the user select a mode to use. Prints choice in xrandr option format
-# (eg, '--mode 800x600' or '--auto') to stdout
-# Global variables:
-#  XRANDR_TXT
-#  CONNECTED_OUTPUT
-#  XRANDR_CMD (via primary_set())
+# Display Output Options for Given Monitor
 # Arguments:
 #  $1 - name of which output we are working with
 # Returns:
-#  257=bad arguements; given output ($1) not found/connected (TODO)
+#  257=bad arguements; 
 #  258=bad selection
 ################################################################################
 function select_mode() {
@@ -146,9 +134,7 @@ function select_mode() {
 
   if [[ -z $1 ]] && return "${err_bad_args}"
 
-  # TODO: make this not ugly. A better sed should negate the need for cut/grep
-  # Should probably parse (sed) seperately then assign to the array. Or not
-  # use an array at all.
+  # Not elegant but works for now, sed command could be addressed later and improved 
   menu="$(echo \"${XRANDR_TXT}\" \
     | sed -n '/^'$1' /,/^[^ ]/ s/ * //p' \
     | cut -d ' ' -f 1 \
@@ -165,11 +151,7 @@ function select_mode() {
 }
 
 ################################################################################
-# Checks to see if all the outputs have been configured
-# global variables:
-#  OUTPUT_CONFIGURED
-# Arguments:
-#  none
+# Verify Configuration of Attached Monitors 
 # Returns:
 #  0 - all outputs are configured
 #  257 - at least 1 output not configured
@@ -186,19 +168,19 @@ function all_outputs_configured() {
 
 function environment_check() {
   if ! command -v cat &>/dev/null; then
-    echo 'You seem to be missing coreutils. You'\''re gonna have a bad time.' >&2
+    echo 'You seem to be missing coreutils. Please install it from your distribution package manager in order to run this application.' >&2
     exit 255
   elif ! command -v grep &>/dev/null; then
-    echo 'grep seems to be missing. You'\''re gonna have a bad time.' >&2
+    echo 'Grep seems to be missing. Please install this from your choice of package manager in order to proceed.' >&2
     exit 255
   elif ! command -v xrandr &>/dev/null; then
-    echo "Try xrandr-dmenu without xrandr, and you're gonna have a bad time." >&2
+    echo "XRANDR does not seem to be installed and as you can imagine is vital to the execution of this application which is presenting you with a front end for it. You must have forgotten to install it during the reinstallation period (again). Please do so in order to proceed in a meaningful manner." >&2
     exit 255
 elif ! command -v rofi &>/dev/null; then
-    echo "Try xrandr-dmenu without dmenu, and you're gonna have a bad time." >&2
+    echo "Either dmenu itself or dmenu-rofi is needed in order to provide you with an interface with which you can interact with. Thus you may choose either, but at least one will be required to proceed." >&2
     exit 255
   elif ! xset q &>/dev/null; then
-    echo 'Woah there, cowboy! You need to run this from inside X!' >&2
+    echo 'This application requires the use of the X11 system' >&2
     exit 1
   fi
 }
